version: "3"
services:
  python_app:
    build: ./docker
    volumes:
      - ./hdf5/:/src/hdf5/
      - ./IsolatedSignLanguage/:/src/IsolatedSignLanguage/
    container_name: python_handlangage
    stdin_open: true

    